name: Bash
on:
  push:
    branches:
      - dev

jobs:  
  changedFilesList: 
    runs-on: ubuntu-latest
    steps:
      - name : printpython 
      - run: python write-env.py
      - run: echo ${{ env.MY_VAR }}
  