name: example
on: push
jobs:
  comment:
    name: Add checkout and pull commands
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@dev
      - uses: smit-darji/comment-on-pr@dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: template.md
        run: echo "hi"