name: Bash
on:
  push:
    branches:
      - dev

jobs:  
  changedFilesList: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v1
    - name : run
      run: |
        python test.py
    - name : pritn
      run : |
          echo ${{ env.MY_VAR }}
  