name: Bash
on:
  push:
    branches:
      - dev

jobs:  
  changedFilesList: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name : print python 
      - run: python test.py
      - run: echo ${{ env.MY_VAR }}
  